In [3]:
import torch

In [5]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

x * y

tensor([10.,  3.])

In [7]:
x = torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [9]:
x.shape

torch.Size([2, 5])

In [4]:
y = torch.rand([2,5])
y

tensor([[8.9560e-02, 6.6501e-01, 5.6485e-01, 6.1085e-01, 5.4072e-01],
        [7.1655e-01, 4.3661e-01, 1.6838e-04, 4.9423e-01, 9.8213e-01]])

In [5]:
y.view([1,10])

tensor([[8.9560e-02, 6.6501e-01, 5.6485e-01, 6.1085e-01, 5.4072e-01, 7.1655e-01,
         4.3661e-01, 1.6838e-04, 4.9423e-01, 9.8213e-01]])